
OUTPUT_ARCH(riscv)
MEMORY
{
	SRAM : ORIGIN = 0x08000000, LENGTH = 200K
	FLASH : ORIGIN = 0x21000000, LENGTH = 8M
	RAM : ORIGIN = 0x40000000, LENGTH = 80M
}

REGION_ALIAS("REGION_TEXT", SRAM);
REGION_ALIAS("REGION_RODATA", SRAM);
REGION_ALIAS("REGION_DATA", SRAM);
REGION_ALIAS("REGION_BSS", SRAM);
REGION_ALIAS("REGION_HEAP", SRAM);
REGION_ALIAS("REGION_STACK", SRAM);

_max_hart_id = 4;
_stack_start = ORIGIN(SRAM) + LENGTH(SRAM);
_hart_stack_size = 4K;

INCLUDE link.x
